[scripts] make script more resilient
Signed-off-by: Christopher Hall <hsw@bitmark.com>

diff --git a/scripts/bitmark-repo b/scripts/bitmark-repo
--- a/scripts/bitmark-repo
+++ b/scripts/bitmark-repo
@@ -74,14 +74,34 @@ CLI() {
   done
   user="${1}"; shift
   [ X"${verbose}" = X"yes" ] && printf '\033[1;33mCLI[%s]: \033[1;31m%s\033[0m\n' "${network}/${user}" "$*"
-  r=$(bitmark-cli -i "${user}" -p "${password}" -n "${network}" "$@" 2>&1)
-  if [ X"${check}" = X"yes" -a $? -ne 0 ]
-  then
-    [ -z "${r}" ] && r='unknown error: stdout empty'
-    r=$(jq --null-input --arg error "${r}" '{error:$error}')
-    return 1
-  fi
-  return 0
+
+  while :
+  do
+    r=$(bitmark-cli -i "${user}" -p "${password}" -n "${network}" "$@" 2>&1)
+    if [ $? -ne 0 ]
+    then
+      case "${r}" in
+        ('terminated with error: not available during synchronise')
+          sleep 30
+          ;;
+        ('terminated with error: connection is shut down')
+          sleep 30
+          ;;
+        ('terminated with error: dial '*)
+          sleep 60
+          ;;
+        (*)
+          [ -z "${r}" ] && r='unknown error: stdout empty'
+          [ X"${verbose}" = X"yes" ] && printf '\033[1;33mCLI[%s]: error: \033[1;31m%s\033[0m\n' "${network}/${user}" "${r}"
+          # make JSON: {"error": "string"}
+          r=$(jq --null-input --arg error "${r}" '{error:$error}')
+          return 1
+          ;;
+      esac
+      continue
+    fi
+    return 0
+  done
 }
 
 PRETTY() {
